language: c
os: linux
dist: trusty
sudo: required

branches:
  except:
  - builds

compiler:
  - gcc

before_install:
  - .travis/install_ssh_id.sh
  - unset SSH_ID

before_script:
  - . ./.travis/setup_env.sh

script:
  - . ./.travis/build.sh "${PWD}/.travis/tmp" "${PWD}/.travis/out"

deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
